from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas
from reportlab.lib import colors
from reportlab.lib.units import inch
import os
from datetime import datetime

LOGO_PATH = "backend/assets/logo.png"   # <-- Your logo path
OUTPUT_DIR = "generated_pdfs"

def generate_pdf(appointment_id, patient_name, doctor_name, diagnosis, treatment,
                 medication, dosage, instructions):

    if not os.path.exists(OUTPUT_DIR):
        os.makedirs(OUTPUT_DIR)

    file_path = f"{OUTPUT_DIR}/prescription_{appointment_id}.pdf"
    c = canvas.Canvas(file_path, pagesize=A4)

    width, height = A4

    # -------------------- LOGO --------------------
    try:
        c.drawImage(LOGO_PATH, width/2 - 80, height - 120, width=160, height=80, preserveAspectRatio=True)
    except:
        pass

    # -------------------- HEADER --------------------
    c.setFont("Helvetica-Bold", 16)
    c.drawCentredString(width/2, height - 140, "MediMate Digital Clinic")
    c.setFont("Helvetica", 11)
    c.drawCentredString(width/2, height - 160, "Smart OPD Prescription & Case Paper")

    # Horizontal line
    c.setStrokeColor(colors.black)
    c.setLineWidth(1)
    c.line(40, height - 170, width - 40, height - 170)

    # -------------------- PATIENT DETAILS --------------------
    c.setFont("Helvetica-Bold", 12)
    c.drawString(40, height - 200, "Patient Details:")

    c.setFont("Helvetica", 11)
    y = height - 220
    c.drawString(60, y, f"Name: {patient_name}")
    c.drawString(300, y, f"Appointment ID: {appointment_id}")

    y -= 20
    c.drawString(60, y, f"Date: {datetime.today().strftime('%d-%m-%Y')}")
    y -= 30

    # -------------------- DOCTOR DETAILS --------------------
    c.setFont("Helvetica-Bold", 12)
    c.drawString(40, y, "Doctor Details:")
    y -= 20

    c.setFont("Helvetica", 11)
    c.drawString(60, y, f"Doctor Name: {doctor_name}")
    y -= 40

    # -------------------- DIAGNOSIS --------------------
    c.setFont("Helvetica-Bold", 12)
    c.drawString(40, y, "Diagnosis:")
    y -= 20

    c.setFont("Helvetica", 11)
    c.drawString(60, y, diagnosis)
    y -= 40

    # -------------------- TREATMENT --------------------
    c.setFont("Helvetica-Bold", 12)
    c.drawString(40, y, "Treatment:")
    y -= 20

    c.setFont("Helvetica", 11)
    text_obj = c.beginText(60, y)
    for line in treatment.split("\n"):
        text_obj.textLine(line)
    c.drawText(text_obj)
    y -= 60

    # -------------------- PRESCRIPTION TABLE --------------------
    c.setFont("Helvetica-Bold", 12)
    c.drawString(40, y, "Prescription:")
    y -= 30

    table_y = y
    c.setFont("Helvetica-Bold", 11)

    c.drawString(60, table_y, "Medication")
    c.drawString(200, table_y, "Dosage")
    c.drawString(330, table_y, "Instructions")

    c.setLineWidth(0.5)
    c.line(40, table_y - 5, width - 40, table_y - 5)

    c.setFont("Helvetica", 11)
    table_y -= 25
    c.drawString(60, table_y, medication)
    c.drawString(200, table_y, dosage)
    c.drawString(330, table_y, instructions)

    # -------------------- FOOTER --------------------
    c.setFont("Helvetica", 9)
    c.setFillColor(colors.grey)
    c.drawCentredString(width/2, 30, "This is a digital case paper generated by MediMate.")
    c.drawCentredString(width/2, 15, "© 2025 MediMate HealthTech — All Rights Reserved")

    c.save()
    return file_path
